apiVersion: v1
kind: Service
metadata:
  labels:
    service: zookeeper
  name: zookeeper
spec:
  selector:
      service: zookeeper
  ports:
    - name: "zoo-port"
      port: 2181
      targetPort: 2181